### ISSUE TITLE
Joseph: Implement the MySQL Database

### ISSUE THREAD

**Issue by JaspreetKhela** [Group2Project2UofTCoding/coworkers#6]

**Comment by ankurshahi80** [comment]
Manager api is not working.
<img width="1028" alt="Screen Shot 2021-07-28 at 10 52 25 AM" src="https://user-images.githubusercontent.com/79622822/127344344-6dcb6228-0953-4847-9fae-a17f83188eb7.png">

**Comment by ankurshahi80** [comment]
<img width="1026" alt="Screen Shot 2021-07-28 at 10 52 50 AM" src="https://user-images.githubusercontent.com/79622822/127344410-6a7a4b21-181c-49ea-be0c-386b664f758f.png">
Unable to add a manager.

**Comment by pravton** [comment]
Can you try dropping all your tables, and test it. I made some changes, which you may need to delete the tables..

**Comment by ankurshahi80** [comment]
![image](https://user-images.githubusercontent.com/79622822/127345819-66c13e82-abc6-454b-90ed-4eddff8e3bcd.png)
It wouldn't drop the tables and recreate it. Please check the error in the terminal.

**Comment by pravton** [comment]
Can you try dropping the coworkers_db database from mysql and recreating using the schema and try it? It should work.

**Comment by ankurshahi80** [comment]
That worked with the get all managers api, but I am still not able to add a manager with the following JSON {
	"username": "Ankur",
	"email": "ankur9@gmail.com",
	"password": "ankur"
have we changed the data structure. I see an employee id field and manager_name twice .

**Comment by pravton** [comment]
Yes, but I think something messed up with merges, We don't really need the manager_name anymore. We just need the employee if there any and it's gonna pull all the information. We don't need the department as well. I will push the updated changes in a bit

**Comment by ankurshahi80** [comment]
Okay. The login is working now.

**Comment by ankurshahi80** [comment]
I fixed the add feature. Let me push the changes first, please hold on.

**Comment by ankurshahi80** [comment]
Fixed Signup, login and logout functionality, and pushed then to develop. Please accept.

**Comment by pravton** [comment]
Sure, let me pull that and test it, because I am making some changes in the model. and I will push it back
